import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { AuthProvider } from '@descope/nextjs-sdk';

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider projectId="P2k3OEw2g9n2xlyfmUlAFxI1GpDF">

        <div className="mx-6 md:mx-16">
        <Header />
        {children}
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
